name: Pre-Release

on:
  pull_request:
    branches: ["main", "main-*"]

permissions:
  contents: read

env:
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  PYTHONUTF8: 1

jobs:
  versioning:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run TinySemVer
        uses: ashvardanian/tinysemver@v2.1.1
        with:
          verbose: "true"
          version-file: "VERSION"
          update-version-in: |
            Cargo.toml:^version = "(\d+\.\d+\.\d+)"
            package.json:"(\d+\.\d+\.\d+)"
            javascript/@numkong-linux-x64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-linux-arm64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-darwin-x64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-darwin-arm64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-win32-x64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-win32-arm64/package.json:"version": "(\d+\.\d+\.\d+)"
            CMakeLists.txt:VERSION (\d+\.\d+\.\d+)
          update-major-version-in: |
            include/numkong/capabilities.h:^#define NK_VERSION_MAJOR (\d+)
          update-minor-version-in: |
            include/numkong/capabilities.h:^#define NK_VERSION_MINOR (\d+)
          update-patch-version-in: |
            include/numkong/capabilities.h:^#define NK_VERSION_PATCH (\d+)
          dry-run: "true"

  wheels:
    name: Build Wheels
    uses: ./.github/workflows/_wheels.yml
    secrets: inherit
