name: Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

jobs:
  versioning:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run TinySemVer
        uses: ashvardanian/tinysemver@v2.1.1
        with:
          verbose: "true"
          version-file: "VERSION"
          update-version-in: |
            Cargo.toml:^version = "(\d+\.\d+\.\d+)"
            package.json:"(\d+\.\d+\.\d+)"
            javascript/@numkong-linux-x64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-linux-arm64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-darwin-x64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-darwin-arm64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-win32-x64/package.json:"version": "(\d+\.\d+\.\d+)"
            javascript/@numkong-win32-arm64/package.json:"version": "(\d+\.\d+\.\d+)"
            CMakeLists.txt:VERSION (\d+\.\d+\.\d+)
          update-major-version-in: |
            include/numkong/capabilities.h:^#define NK_VERSION_MAJOR (\d+)
          update-minor-version-in: |
            include/numkong/capabilities.h:^#define NK_VERSION_MINOR (\d+)
          update-patch-version-in: |
            include/numkong/capabilities.h:^#define NK_VERSION_PATCH (\d+)
          dry-run: "false"
          push: "true"
          create-release: "true"
          github-token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  rebase:
    name: Rebase Dev. Branch
    needs: versioning
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Perform rebase
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main-dev
          git rebase origin/main
      - name: Push changes
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.SEMANTIC_REBASE_TOKEN }}
          branch: main-dev
          unprotect_reviews: True
          force: True
